In [2]:
import warnings
warnings.filterwarnings('ignore')

In [32]:
import scrapbook as sb 
import pandas as pd

In [5]:
book = sb.read_notebooks('/Users/manasigude/Academics/Project(ABC_GAN)/ABC_GAN/Regression')

In [38]:
book.scraps

Scraps([('Stats Model MSE',
         Scrap(name='Stats Model MSE', data=2.3221604842124612e-07, encoder='json', display=None)),
        ('Stats Model MAE',
         Scrap(name='Stats Model MAE', data=0.0003861832025725345, encoder='json', display=None)),
        ('Manhattan Distance',
         Scrap(name='Manhattan Distance', data=0.03861832025725345, encoder='json', display=None)),
        ('Euclidean distance',
         Scrap(name='Euclidean distance', data=0.004818880040229742, encoder='json', display=None)),
        ('GAN Model MSE',
         Scrap(name='GAN Model MSE', data=0.0008791809438956094, encoder='json', display=None)),
        ('GAN Model MAE',
         Scrap(name='GAN Model MAE', data=0.022863019734406843, encoder='json', display=None)),
        ('GAN Model Manhattan Distance',
         Scrap(name='GAN Model Manhattan Distance', data=2.2863019734406844, encoder='json', display=None)),
        ('GAN Model Euclidean distance',
         Scrap(name='GAN Model Euclidean distance', data=0.2963730244581927, encoder='json', display=None)),
        ('ABC-GAN Model MSE',
         Scrap(name='ABC-GAN Model MSE', data=0.0020636950090907303, encoder='json', display=None)),
        ('ABC-GAN Model MAE',
         Scrap(name='ABC-GAN Model MAE', data=0.033541463671839446, encoder='json', display=None)),
        ('ABC-GAN Model Manhattan Distance',
         Scrap(name='ABC-GAN Model Manhattan Distance', data=3.3541463671839447, encoder='json', display=None)),
        ('ABC-GAN Model Euclidean distance',
         Scrap(name='ABC-GAN Model Euclidean distance', data=0.4499181558883759, encoder='json', display=None))])

In [40]:
data = []
for nb in book.notebooks:
    nbList = [nb.papermill_dataframe.iloc[1]['value'],
              nb.papermill_dataframe.iloc[2]['value'],
              nb.papermill_dataframe.iloc[0]['value'],
              nb.papermill_dataframe.iloc[3]['value'],
              nb.scraps['Stats Model MSE'].data,
              nb.scraps['GAN Model MSE'].data,
              nb.scraps['ABC-GAN Model MSE'].data,
              nb.scraps['Stats Model MAE'].data,
              nb.scraps['GAN Model MAE'].data,
              nb.scraps['ABC-GAN Model MAE'].data,
              nb.scraps['Manhattan Distance'].data,
              nb.scraps['GAN Model Manhattan Distance'].data,
              nb.scraps['ABC-GAN Model Manhattan Distance'].data,
              nb.scraps['Euclidean distance'].data,
              nb.scraps['GAN Model Euclidean distance'].data,
              nb.scraps['ABC-GAN Model Euclidean Distance'].data]        
    data.append(nbList)

KeyError: 'GAN Model Euclidean Distance'

In [36]:
df = pd.DataFrame(data, columns = ['Features','Sample Size','Mean','Variance',
                                   'Stats Model MSE','GAN MSE','ABC-GAN MSE',
                                   'Stats Model MAE','GAN MAE','ABC-GAN MAE',
                                   'Stats Manhattan Distance','GAN Manhattan Distance','ABC-GAN Manhattan Distance',
                                   'Stats Model Euclidean Distance','GAN Euclidean Distance','ABC-GAN Euclidean Distance'])

In [37]:
df

,Features,Sample Size,Mean,Variance,Stats Model MSE,GAN MSE,ABC-GAN MSE
0,10.0,10.0,1.0,1.00,7.918076e-31,0.001292,0.002614
1,10.0,10.0,1.0,0.10,4.939612e-30,0.002573,0.117498
2,10.0,100.0,0.0,0.10,3.640551e-07,0.000866,0.000911
3,10.0,100.0,0.0,0.01,2.470461e-07,0.000712,0.000868
4,10.0,10.0,1.0,0.01,1.797374e-30,0.001048,0.001210
5,10.0,10.0,0.0,1.00,1.461054e-30,0.249578,0.001358
6,10.0,10.0,0.0,0.10,3.452268e-30,0.001052,0.355005
7,10.0,10.0,0.0,0.01,1.735826e-30,0.321958,0.000921
8,10.0,100.0,1.0,1.00,1.746527e-07,0.000986,0.000847
9,10.0,100.0,1.0,0.10,2.394029e-07,0.000702,0.000977
10,10.0,100.0,1.0,0.01,1.378492e-07,0.000961,0.000735
11,10.0,100.0,0.0,1.00,2.322160e-07,0.000879,0.002064